export const message = {
  SELECT_VACCINE: "Vui lòng thêm ít nhất một vaccine!",
  SELECT_PATIENT: "Vui lòng chọn bệnh nhân!",
  SELECT_DATE: "Vui lòng chọn ngày tiêm!",
  SELECT_TIME: "Vui lòng chọn giờ tiêm!",
  SELECT_FEDDBACK: "Vui lòng nhập đầy đủ thông tin nhận xét và đánh giá.",
  SELECT_COLD_STORAGE: "Vui lòng chọn kho lạnh!",
  ERROR_FETCH_DATA: "Lỗi khi tải dữ liệu!",
  SUCCESS_FETCH_DATA: "Thành công tải dữ liệu",
  SUCCESS_CREATE: "Tạo mới thành công!",
  ERROR_CREATE: "Có lỗi xảy ra khi tạo mới!",
  LOGIN_SUCCESS: "🎉 Đăng nhập thành công!",
  LOGIN_ERROR: "Đăng nhập thất bại!",
  REGISTER_SUCCESS: "🎉 Đăng ký thành công!",
  REGISTER_ERROR: "Đăng ký thất bại!",
  UPDATE_SUCCESS: "Cập nhật thành công",
  UPDATE_ERROR: "Cập nhật thất bại!",
  DELETE_SUCCESS: "Xóa thành công",
  DELETE_ERROR: "Xóa thất bại!",
  PAYMENT_SUCCESS: "🎉 Thanh toán thành công!",
  PAYMENT_ERROR: "❌ Thanh toán thất bại!",
  UPLOAD_SUCCESS: "Tải lên thành công",
  UPLOAD_ERROR: "Tải lên thất bại!",
  CANCEL_SUCCESS: "Hủy lịch thành công. Đợi xác nhận",
  CANCEL_ERROR: "Hủy lịch thất bại! ",
  REQUEST_SUCCESS: "Xác nhận yêu cầu thành công",
  REQUEST_ERROR: "Lỗi không thể phê duyệt!",
  CHANGE_SCHEDULE_SUCCESS: "Đổi lịch thành công",
  CHANGE_SCHEDULE_ERROR: "Đổi lịch thất bại! ",
  FEDDBACK_SUCCESS: "Gửi nhận xét thành công",
  FEDDBACK_ERROR: "Gửi nhận xét thất bại!",
  VERIFY_SUCCESS: "Xác thực thành công",
  VERIFY_ERROR: "Xác thực thất bại!",
  COLDSTORAGE_SUCCESS: "Tạo kho lạnh thành công",
  COLDSTORAGE_ERROR: "Tạo kho lạnh thất bại!",
  CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
  CHANGE_PASSWORD_ERROR: "Đổi mật khẩu thất bại!",
  CHANGE_STATUS_COLD_STORAGE_ERROR:
    "Không thể tắt kho khi vẫn còn vaccine bên trong",
  IMPORT_VACCINE_TO_COLD_STORAGE_SUCCESS: "Cất vaccine vào kho thành công",
  IMPORT_VACCINE_TO_COLD_STORAGE_ERROR: "Cất vaccine vào kho thất bại!",
};
